'use client'

// Block type definition — each represents a type of timeline section a user can add
export type BlockType = {
  id: string                    // unique identifier e.g. 'morning-routine', 'work', 'fitness'
  name: string                  // display name e.g. 'Morning Routine'
  description: string           // short description for the config screen
  icon: string                  // lucide icon name
  defaultStartTime: string      // e.g. '06:30'
  defaultEndTime: string        // e.g. '08:30'
  repeatable: boolean           // can user add multiple instances? (e.g. multiple work blocks)
  category: 'routine' | 'work' | 'health' | 'meals' | 'social' | 'rest' | 'focus' | 'custom'
  component: string             // component key for the renderer
}

// All available block types users can add to their schedule
export const BLOCK_REGISTRY: BlockType[] = [
  // ─── Routine ────────────────────────────────────────────────────────────────
  {
    id: 'morning-routine',
    name: 'Morning Routine',
    description: 'Start your day — coffee, supplements, intentions.',
    icon: 'Sunrise',
    defaultStartTime: '06:30',
    defaultEndTime: '08:30',
    repeatable: false,
    category: 'routine',
    component: 'MorningRoutine',
  },
  {
    id: 'hard-stop',
    name: 'Hard Stop',
    description: 'A firm boundary — no more work or eating.',
    icon: 'OctagonAlert',
    defaultStartTime: '18:00',
    defaultEndTime: '18:00',
    repeatable: true,
    category: 'routine',
    component: 'HardStop',
  },
  {
    id: 'skincare',
    name: 'Skincare / Grooming',
    description: 'Morning or evening skincare routine.',
    icon: 'Sparkles',
    defaultStartTime: '07:00',
    defaultEndTime: '07:15',
    repeatable: true,
    category: 'routine',
    component: 'GenericBlock',
  },
  {
    id: 'commute',
    name: 'Commute',
    description: 'Travel time — listen to podcasts or audiobooks.',
    icon: 'Car',
    defaultStartTime: '08:00',
    defaultEndTime: '08:30',
    repeatable: true,
    category: 'routine',
    component: 'GenericBlock',
  },
  {
    id: 'chores',
    name: 'Chores / Housework',
    description: 'Cleaning, laundry, tidying up.',
    icon: 'Home',
    defaultStartTime: '09:00',
    defaultEndTime: '10:00',
    repeatable: true,
    category: 'routine',
    component: 'GenericBlock',
  },
  {
    id: 'errands',
    name: 'Errands',
    description: 'Groceries, appointments, things to handle.',
    icon: 'ShoppingCart',
    defaultStartTime: '10:00',
    defaultEndTime: '11:00',
    repeatable: true,
    category: 'routine',
    component: 'GenericBlock',
  },

  // ─── Work ───────────────────────────────────────────────────────────────────
  {
    id: 'work',
    name: 'Work Block',
    description: 'Focused work session with progress tracking.',
    icon: 'Briefcase',
    defaultStartTime: '09:00',
    defaultEndTime: '17:00',
    repeatable: true,
    category: 'work',
    component: 'WorkBlock',
  },
  {
    id: 'personal-work',
    name: 'Personal Work / Side Project',
    description: 'Time for your own business or projects.',
    icon: 'Laptop',
    defaultStartTime: '08:30',
    defaultEndTime: '12:00',
    repeatable: true,
    category: 'work',
    component: 'WorkBlock',
  },
  {
    id: 'study',
    name: 'Study / Learning',
    description: 'Courses, textbooks, skill development.',
    icon: 'GraduationCap',
    defaultStartTime: '19:00',
    defaultEndTime: '20:00',
    repeatable: true,
    category: 'work',
    component: 'GenericBlock',
  },

  // ─── Focus ──────────────────────────────────────────────────────────────────
  {
    id: 'meditation',
    name: 'Meditation / Mindfulness',
    description: 'Breathing exercises, guided meditation, stillness.',
    icon: 'Brain',
    defaultStartTime: '06:30',
    defaultEndTime: '07:00',
    repeatable: true,
    category: 'focus',
    component: 'GenericBlock',
  },
  {
    id: 'journaling',
    name: 'Journaling / Reflection',
    description: 'Write your thoughts, gratitude, or morning pages.',
    icon: 'BookOpen',
    defaultStartTime: '06:45',
    defaultEndTime: '07:15',
    repeatable: true,
    category: 'focus',
    component: 'GenericBlock',
  },
  {
    id: 'reading',
    name: 'Reading',
    description: 'Books, articles, or long-form content.',
    icon: 'BookOpen',
    defaultStartTime: '21:00',
    defaultEndTime: '22:00',
    repeatable: true,
    category: 'focus',
    component: 'GenericBlock',
  },
  {
    id: 'creative',
    name: 'Creative Time',
    description: 'Music, art, writing, or any creative pursuit.',
    icon: 'Palette',
    defaultStartTime: '19:00',
    defaultEndTime: '20:00',
    repeatable: true,
    category: 'focus',
    component: 'GenericBlock',
  },
  {
    id: 'screen-free',
    name: 'Screen-Free Time',
    description: 'Phones and screens away. Be present.',
    icon: 'MonitorOff',
    defaultStartTime: '20:00',
    defaultEndTime: '21:00',
    repeatable: true,
    category: 'focus',
    component: 'GenericBlock',
  },

  // ─── Health ─────────────────────────────────────────────────────────────────
  {
    id: 'fitness',
    name: 'Fitness / Workout',
    description: 'Your configured workout routine.',
    icon: 'Dumbbell',
    defaultStartTime: '12:00',
    defaultEndTime: '13:00',
    repeatable: false,
    category: 'health',
    component: 'FitnessSection',
  },
  {
    id: 'walk',
    name: 'Daily Walk',
    description: '30–60 min walk, solo or with family.',
    icon: 'Footprints',
    defaultStartTime: '18:00',
    defaultEndTime: '21:00',
    repeatable: false,
    category: 'health',
    component: 'EveningWalk',
  },
  {
    id: 'water',
    name: 'Water Tracker',
    description: 'Stay hydrated — track 8 glasses a day.',
    icon: 'Droplets',
    defaultStartTime: '06:30',
    defaultEndTime: '21:00',
    repeatable: false,
    category: 'health',
    component: 'WaterTracker',
  },
  {
    id: 'supplements-midday',
    name: 'Midday Supplements',
    description: 'Take your midday supplements.',
    icon: 'Pill',
    defaultStartTime: '12:00',
    defaultEndTime: '13:00',
    repeatable: false,
    category: 'health',
    component: 'SupplementsMidday',
  },
  {
    id: 'supplements-evening',
    name: 'Evening Supplements',
    description: 'Take your evening supplements.',
    icon: 'Pill',
    defaultStartTime: '19:00',
    defaultEndTime: '20:00',
    repeatable: false,
    category: 'health',
    component: 'SupplementsEvening',
  },
  {
    id: 'stretching',
    name: 'Stretching / Yoga',
    description: 'Flexibility work, yoga flow, or mobility.',
    icon: 'Activity',
    defaultStartTime: '07:00',
    defaultEndTime: '07:30',
    repeatable: true,
    category: 'health',
    component: 'GenericBlock',
  },
  {
    id: 'nap',
    name: 'Nap / Power Rest',
    description: '20-minute power nap to recharge.',
    icon: 'Moon',
    defaultStartTime: '14:00',
    defaultEndTime: '14:20',
    repeatable: false,
    category: 'health',
    component: 'GenericBlock',
  },

  // ─── Meals ──────────────────────────────────────────────────────────────────
  {
    id: 'meals',
    name: 'Meals',
    description: 'Track breakfast, lunch, and supper with AI.',
    icon: 'Utensils',
    defaultStartTime: '10:00',
    defaultEndTime: '18:00',
    repeatable: false,
    category: 'meals',
    component: 'MealTabs',
  },
  {
    id: 'lunch-break',
    name: 'Lunch Break',
    description: 'Step away from work — eat and recharge.',
    icon: 'Coffee',
    defaultStartTime: '12:00',
    defaultEndTime: '13:00',
    repeatable: false,
    category: 'meals',
    component: 'GenericBlock',
  },

  // ─── Social ─────────────────────────────────────────────────────────────────
  {
    id: 'family-time',
    name: 'Family Time',
    description: 'Be present. Log activities together.',
    icon: 'Users',
    defaultStartTime: '18:00',
    defaultEndTime: '20:00',
    repeatable: false,
    category: 'social',
    component: 'FamilyTime',
  },
  {
    id: 'social',
    name: 'Social Time',
    description: 'Hang out with friends, call someone.',
    icon: 'MessageCircle',
    defaultStartTime: '19:00',
    defaultEndTime: '20:00',
    repeatable: true,
    category: 'social',
    component: 'GenericBlock',
  },
  {
    id: 'date-night',
    name: 'Date Night',
    description: 'Quality time with your partner.',
    icon: 'Heart',
    defaultStartTime: '19:00',
    defaultEndTime: '22:00',
    repeatable: false,
    category: 'social',
    component: 'GenericBlock',
  },
  {
    id: 'pet-care',
    name: 'Pet Care',
    description: 'Feed, walk, or play with your pet.',
    icon: 'Dog',
    defaultStartTime: '07:00',
    defaultEndTime: '07:30',
    repeatable: true,
    category: 'social',
    component: 'GenericBlock',
  },

  // ─── Rest ───────────────────────────────────────────────────────────────────
  {
    id: 'movie-night',
    name: 'Movie / Wind Down',
    description: 'Relax and wind down for the night.',
    icon: 'Film',
    defaultStartTime: '20:00',
    defaultEndTime: '22:00',
    repeatable: false,
    category: 'rest',
    component: 'MovieNight',
  },
  {
    id: 'bedtime-routine',
    name: 'Bedtime Routine',
    description: 'Wind down — lights low, no screens, prepare for sleep.',
    icon: 'BedDouble',
    defaultStartTime: '21:30',
    defaultEndTime: '22:00',
    repeatable: false,
    category: 'rest',
    component: 'GenericBlock',
  },

  // ─── Custom ─────────────────────────────────────────────────────────────────
  {
    id: 'custom',
    name: 'Custom Block',
    description: 'Create your own block with a checklist.',
    icon: 'SquarePlus',
    defaultStartTime: '09:00',
    defaultEndTime: '10:00',
    repeatable: true,
    category: 'custom',
    component: 'GenericBlock',
  },
]

export function getBlockType(id: string): BlockType | undefined {
  return BLOCK_REGISTRY.find((b) => b.id === id)
}
